os: linux
language: python
dist: xenial
cache: pip
python:
- '3.6'
- '3.7'
env:
  global:
  - secure: wV6LH0WHmYbLU7BPC2iARyAJFvhBn/LSWNSlB0SI6iT4dar8877IOiGzcPV+u4SD4OmLTvjIKdMf9FzJ3JBDHzONw7cH9Be7ibX6eBubJ1qsASDjXTO9p4HOHRhY9wTXpPlsuWa2LzEmYxO3Uy0jOcD3EBYGH3mattx9fnwDrVPi1Ng0BHUvC1CG4a+CVRwN1C0LODgkd59OQYpoYY8cYXkT7/BDnNZt/htamu/NiOl2+/Fr1wRgTh2MfZfbpxCvC/O9URErl1OaU8EJjaXH/sY97v6SLISdjFvnREj3Xaj6YFaugYJog1q7lE+edx1G0mEkx4yq9zZvW2uYaHqn3kGsvr3ul2usBjZ5y8qpMg3IYkxgAiBK0B36pJUsMjXTZtz7xK62XTrRBGEqD/kAsUZQLNsbwidMCseFR66vLfMvJqv/fuHYAdffbvJCLeuNfUB1e3oeIgECKzXlMcOPLu+iojZiJnizdEhPvx2yWY5Rooncv3CZB3Tnye7fFkMfg5IN2PiRfrywsX+S03NzuCJ+nC094Dte4wZgnMj6nn/bppHY6jc4g17eLv82T+RnA+b2KvyN9dOliaS+0RTs5TmAilR802PC6WvnHO0pVKXE2dK9E72m/OP9RGFXa3pVT2HfV6ETkN9Nf8joM0IegyEcFww74w6QN4vPimiFH4I=
  matrix:
  - TORCH_VER="1.0.1"
  - TORCH_VER="1.1.0"
  - TORCH_VER="1.2.0"
  - TORCH_VER="1.3.0"
  - TORCH_VER="1.4.0" 
install:
- pip install --upgrade pip
- pip install --progress-bar off torch==$TORCH_VER
- pip install --progress-bar off .[extras]
- if [[ $TORCH_VER == "1.4.0" ]]; then pip install pylint==2.4.4 flake8==3.7.9; fi
- if [[ $TORCH_VER != "1.0.1" ]]; then pip install mypy==0.761; fi
- pip install pytest
- pip install coverage codecov
script:
- if [[ $TORCH_VER == "1.4.0" ]]; then pylint texar/ examples/; fi
- if [[ $TORCH_VER == "1.4.0" ]]; then flake8 texar/ examples/; fi
- if [[ $TORCH_VER != "1.0.1" ]]; then mypy .; fi
- if [[ $TORCH_VER != "1.0.1" ]]; then _rc=0; for dir in `echo examples/**/`; do mypy
  $dir || _rc=$?; done && [[ $_rc == 0 ]]; fi
- coverage run -m pytest
after_success:
- codecov
- scripts/travis_after_success.sh
jobs:
  include:
  - stage: docs
    python: '3.7'
    install:
    - pip install --upgrade pip
    - pip install --progress-bar off -r requirements.txt
    - pip install --progress-bar off .[extras]
    - sudo apt-get install libenchant1c2a myspell-en-us
    - pip install --progress-bar off -r docs/requirements.txt
    script:
    - cd docs
    - sphinx-build -W -b html -d _build/doctrees . _build/html
    - sphinx-build -W -b spelling -d _build/doctrees . _build/spelling
  fast_finish: true
  exclude:
  - python: '3.6'
    env: TORCH_VER="1.0.1"
  - python: '3.6'
    env: TORCH_VER="1.2.0"
  - python: '3.6'
    env: TORCH_VER="1.3.0"
  - python: '3.6'
    env: TORCH_VER="1.4.0"
notifications:
  email: false
